// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCEoNnaWnEiB4pmhs6El5CY1Kdk2g3a14',
    appId: '1:303473931510:web:fd54942acae8a69a66e8d7',
    messagingSenderId: '303473931510',
    projectId: 'login-app-flutter-98a01',
    authDomain: 'login-app-flutter-98a01.firebaseapp.com',
    storageBucket: 'login-app-flutter-98a01.appspot.com',
    measurementId: 'G-ZBXENQ94HP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuR14dEuHuNkeVrHR_-RGuaHATqpCzzA8',
    appId: '1:303473931510:android:59cb70ba2903883766e8d7',
    messagingSenderId: '303473931510',
    projectId: 'login-app-flutter-98a01',
    storageBucket: 'login-app-flutter-98a01.appspot.com',
  );
}
